name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer
      - run: composer install --no-interaction --prefer-dist --no-progress
      - name: PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon.dist
      - name: PHP-CS-Fixer (dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
      - name: PHPUnit
        run: vendor/bin/phpunit -c phpunit.xml.dist


